version: '3.8'
services:
  minishell-test:
    build: .
    volumes:
      - .:/minishell
    working_dir: /minishell
    stdin_open: true
    tty: true
    environment:
      - USER=root
      - TERM=xterm-256color
    command: /bin/bash
